---
- name: Install weechat
  pacman: state=present name=weechat
- name: Generate client SSL certificate
  shell: >
    su - {{irc_user}} -c 'echo "{{certificate_string}}" | openssl req -nodes -newkey rsa:2048 -keyout ~/.weechat/ssl/client.pem -x509 -days 3650 -out ~/.weechat/ssl/client.pem'
- name: Make log directory
  file: >
    state=directory
    path=/srv/irclogs/
    owner={{irc_user}}
    group={{irc_user}}
- name: Add deploy key for log repo
  github_key: >
    username={{github.username}}
    password={{github.password}}
    repo=irclogs
- name: Clone log repo
  git: >
    dest='/srv/irclogs'
    repo='git@github.com:akerl/irclogs.git'
...

