---
-   name: Install weechat
    pacman: state=present name=weechat

-   name: Make log directory
    file: >
        state=directory
        path=/srv/irclogs/
        owner={{admin.username}}
        group={{admin.username}}
-   name: Copy current log repo to remote
    connection: local
    command: >
        rsync 
        -e "ssh -oUserKnownHostsFile=/dev/null -oStrictHostKeyChecking=no"
        -r {{irc_log_dir}}
        {{admin.username}}@{{inventory_hostname}}:/srv/irclogs/
-   name: Remove remote from log repo
    command: git remote rm origin chdir=/srv/irclogs
-   name: Add cronjob for irc logs
    cron: >
        name=irclogs
        job='(cd /srv/irclogs ; git add --all ; git commit -m "$(date)" ; cd) &>/dev/null'
        cron_file=irclogs
        minute=0
        hour=0
        day='*/2'
        user={{admin.username}}

-   name: Generate client SSL certificate
    shell: >
        su - {{admin.username}}
        -c 'echo "{{certificate_string}}" | openssl req -nodes -newkey rsa:2048 -keyout ~/.weechat/ssl/client.pem -x509 -days 3650 -out ~/.weechat/ssl/client.pem'

-   name: Start weechat for certificate updating
    command: su - {{admin.username}} -c "tmux new-session -d -s irc 'weechat-curses -a'"
-   name: Connect to all networks
    shell: sleep 3; echo "*/connect -all -nojoin" > /home/{{admin.username}}/.weechat/weechat_fifo_$(pgrep weechat)
-   name: Delay to allow servers to connect
    pause: seconds=5

-   name: Load OFTC credentials
    connection: local
    keychain: keychain={{keychain}} service=oftc
    register: oftc
-   name: Load Freenode credentials
    connection: local
    keychain: keychain={{keychain}} service=freenode
    register: freenode

-   name: Generate command list
    template: >
        src=cert_update.j2
        dest=/tmp/cert_update
-   name: Execute commands
    shell: cat /tmp/cert_update > /home/{{admin.username}}/.weechat/weechat_fifo_$(pgrep weechat)
-   name: Remove command list
    file: state=absent path=/tmp/cert_update

-   name: Delay to allow NickServ to handle certificate updates
    pause: seconds=5
-   name: Stop weechat
    command: su - {{admin.username}} -c 'tmux kill-session'

...

