---
- name: Install weechat
  pacman: state=present name=weechat
- name: Generate client SSL certificate
  shell: >
    su - {{irc_user}} -c 'echo "{{certificate_string}}" | openssl req -nodes -newkey rsa:2048 -keyout ~/irc.key -x509 -days 3650 -out ~/irc.cert'
...

