#!/usr/bin/env bash

if [[ -z "$1" ]] ; then
    echo "Please provide a hostname:"
    cat hosts | awk '/^[a-z]+\s?$/ {print $1}' | sort | uniq
    exit
fi

ansible-playbook -l $1 rebuild.yml
ansible-playbook -l $1 deploy.yml

