---
-   hosts: cluster
    gather_facts: no
    roles:
        - credentials
        - deploy
        - kickstart
        - gather_facts
        - packages
        - networking
        - smtp
        - misc
        - users
        - env
        - security
        - longview
        - backups
        - kernel
        - local
        - { role: irc, when: "'irc' in group_names" }
        - { role: dns, when: "'dns' in group_names" }
        - { role: hyped, when: "'hyped' in group_names" }
        - { role: web, when: "'web' in group_names" }
        - finalize
...

