---
- include: common/tasks/credentials.yml

- include: common/tasks/kickstart.yml

- include: common/tasks/packages.yml
- include: common/tasks/networking.yml
- include: common/tasks/smtp.yml
- include: common/tasks/misc.yml
- include: common/tasks/users.yml
- include: common/tasks/env.yml
- include: common/tasks/security.yml
- include: common/tasks/backups.yml
- include: common/tasks/kernel.yml

- include: common/tasks/platform.yml

- include: common/tasks/local.yml

- hosts: web
  roles:
    - web
- hosts: dns
  roles:
    - dns
- hosts: irc
  roles:
    - irc
- hosts: kernel
  roles:
    - kernel

- hosts: cluster
  tasks:
    - name: Pause before reboot
      pause: prompt="Press enter to reboot the server"
    - name: Schedule the reboot
      command: shutdown -r
...

