---
- include: common/tasks/credentials.yml

- include: common/tasks/kickstart.yml

- include: common/tasks/packages.yml
- include: common/tasks/networking.yml
- include: common/tasks/smtp.yml
- include: common/tasks/misc.yml
- include: common/tasks/users.yml
- include: common/tasks/env.yml
- include: common/tasks/security.yml
- include: common/tasks/backups.yml
- include: common/tasks/kernel.yml

- include: common/tasks/platform.yml

- include: common/tasks/local.yml

- hosts: web
  roles:
    - web
- hosts: dns
  roles:
    - dns
- hosts: irc
  roles:
    - irc
- hosts: kernel
  roles:
    - kernel
- hosts: hyped
  roles:
    - hyped

- hosts: cluster
  tasks:
    - name: Check in any config changes
      command: /etc/cron.daily/etcsave nomail
    - name: Send completion email
      mail: >
        from="ansible@{{inventory_hostname}}.{{domain}}"
        subject="Deployment of {{inventory_hostname}}"
        body="Server deployment successful"
    - name: Pause before reboot
      pause: prompt="Press enter to reboot the server"
    - name: Schedule the reboot
      command: shutdown -r
...

