---
- hosts: all
  user: root
  gather_facts: no
  tasks:
    - script: scripts/pacmankeygen.sh
    - raw: pacman -Sy --noconfirm --needed pacman
    - raw: pacman -S --noconfirm --needed python2 python2-pip
- hosts: all
  user: root
  vars_files:
    - resources/common.yml
    - resources/packages.yml
    - resources/modules.yml
    - resources/repos.yml
  tasks:
    - pip: name=$item state=latest
      with_items: $modules
    - pacman: update=yes
    - pacman: name=$item
      with_items: $wantedPackages
    - pacman: name=$item state=absent
      with_items: $unwantedPackages
    - template: src=templates/hostname.j2 dest=/etc/hostname owner=root group=root mode=0644
    - template: src=templates/hosts.j2 dest=/etc/hosts owner=root group=root mode=0644
    - raw: hostname -F /etc/hostname
      tags:
        - test
    - action: ping
...

