---
- hosts: irc
  vars_files:
    - ../vars/common.yml
  tasks:
    - name: Install weechat
      pacman: state=present name=weechat
    - name: Generate client SSL certificate
      shell: >
        su - ${admin_user} -c
        'echo "$certificatestring" |
        openssl req -nodes -newkey rsa:2048 -keyout ~/.weechat/ssl/user -x509 -days 365 -out ~/.weechat/ssl/user'
        creates=/home/${admin_user}/.weechat/ssl/user
...

