---
- hosts: irc
  vars_files:
    - ../vars/common.yml
  tasks:
    - name: Install irssi
      pacman: state=present name=irssi
    - name: Generate client SSL certificate
      shell: >
        su - ${admin_user} -c
        'echo "$certificatestring" |
        openssl req -nodes -newkey rsa:2048 -keyout ${admin_user}.key -x509 -days 3650 -out ${admin_user}.cert'
        creates=/home/${admin_user}/.irssi/certs/user
...

