---
- hosts: nameserver
  tasks:
    - name: Install NSD
      pacman: state=present name=nsd
    - name: Drop NSD config into place
      file: state=link src=/opt/dns/nsd.conf path=/etc/nsd/nsd.conf
    - name: Punch IPv4 firewall holes for NSD
      lineinfile: >
        dest=/etc/iptables/iptables.rules
        insertafter='# Services go here'
        regexp='-A INPUT -p ${item} --dport 53 -j ACCEPT'
        line='-A INPUT -p ${item} --dport 53 -j ACCEPT'
      with_items: [ tcp, udp ]
    - name: Punch IPv6 firewall holes for NSD 
      lineinfile: >
        dest=/etc/iptables/ip6tables.rules
        insertafter='# Services go here'
        regexp='-A INPUT -p ${item} --dport 53 -j ACCEPT'
        line='-A INPUT -p ${item} --dport 53 -j ACCEPT'
      with_items: [ tcp, udp ]
    - name: Generate the initial NSD database
      command: nsdc rebuild
    - name: Enable and start NSD
      service: name=nsd.service action=restart enabled=yes
...

