---
- name: Identify swap device
  command: swapon --show=NAME --noheadings
  register: swapdev
- name: Identify root device
  command: awk '/ext/ { print $1 }' /etc/fstab
  register: rootdev
- name: Identify root format
  command: awk '/ext/ { print $3 }' /etc/fstab
  register: rootformat
- name: Generate /etc/fstab
  template: src=../files/fstab.j2 dest=/etc/fstab
...

