---
- name: Recreate /boot/grub
  file: state=directory path=/boot/grub

- name: Clear old grub menu.lst
  file: state=absent path=/boot/grub/menu.lst
- name: Roll kernel
  command: /opt/roller/autoroll.py
...

