---
- hosts: kvm
  tasks:
    - name: Install grub-legacy
      shell: /usr/local/bin/packer -S grub-legacy --noconfirm > /dev/null creates=/sbin/grub
    - name: Copy grub files into place
      shell: "cp /usr/lib/grub/i386-pc/* /boot/grub/"
    - name: Generate grub builder
      template: src=../files/grub.j2 dest=/root/grubcmd
    - name: Execute grub builder
      shell: cat /root/grubcmd | grub --no-curses
    - name: Remove grub builder template
      file: state=absent path=/root/grubcmd
...

