---
- name: Setting timezone
  command: timedatectl set-timezone US/Eastern
- name: Enable UTF-8
  lineinfile: dest=/etc/locale.gen line='en_US.UTF-8 UTF-8' regexp='#?en_US.UTF-8 UTF-8'
- name: Enable ISO-8859-1
  lineinfile: dest=/etc/locale.gen line='en_US ISO-8859-1' regexp='#?en_US ISO-8859-1'
- name: Regenerate locales
  command: locale-gen
- name: Drop in locale.conf
  copy: src=../files/locale.conf dest=/etc/locale.conf
...

