---
- name: Install python2 modules
  pip: >
    name=$item 
    state=latest 
    pip=pip2
  with_items: ${modules.python2}

- name: Drop in pacman mirrorlist
  copy: >
    src=../files/mirrorlist 
    dest=/etc/pacman.d/mirrorlist
- name: Drop in pacman config
  copy: >
    src=../files/pacman.conf 
    dest=/etc/pacman.conf

- name: Upgrade packages
  pacman: update=yes
- name: Install specified packags
  pacman: state=present name=$item
  with_items: ${packages.add}
- name: Remove specified packages
  pacman: state=absent name=$item
  with_items: ${packages.remove}

- name: Check known pacnews
  pacnew: >
    path=${item.path} 
    new=${item.new} 
    old=${item.old} 
    keep=${item.keep}
  with_items: ${pacnews}
- name: Check for remaining pacnews
  pacnew: check_all=yes

- name: Install python3 modules
  pip: >
    name=$item 
    state=latest 
    pip=pip3
  with_items: ${modules.python3}

- name: Reload systemd units
  raw: systemctl --system daemon-reload
...

