---
- name: Check for xen status
  shell: cat /sys/hypervisor/type 2>/dev/null || true
  register: xencheck
- name: Group by xen status
  group_by: key=${xencheck.stdout}
  when_string: ${xencheck.stdout} != ''
- name: Group by kvm status
  group_by: key=${ansible_virtualization_type}
  when_set: ${ansible_virtualization_type}

- name: Recreate /boot/grub
  file: state=directory path=/boot/grub
...

