---
- shell: cat /sys/hypervisor/type 2>/dev/null || true
  register: xencheck
- group_by: key=${xencheck.stdout}
  when_string: ${xencheck.stdout} != ''
- group_by: key=${ansible_virtualization_type}
  when_set: ${ansible_virtualization_type}

- file: state=absent path=/boot
- file: state=directory path=/boot/grub
...

