---
-   name: Create local QR code image
    connection: local
    command: >
        qrencode
        "otpauth://totp/{{inventory_hostname}}?secret={{twofa.token}}"
        -s 10
        -o /tmp/{{inventory_hostname}}.2fa.png
-   name: Open QR code
    connection: local
    shell: >
        lockfile .block ;
        open /tmp/{{inventory_hostname}}.2fa.png ;
        sleep 3 ;
        rm -f .block
-   name: Delete QR code
    connection: local
    command: rm -f /tmp/{{inventory_hostname}}.2fa.png

-   name: Load GPG pubkey for node
    command: gpg -a --export {{inventory_hostname}}
    register: node_gpgkey
-   include: import_gpg.yml homedir='~/.gnupg'
-   include: import_gpg.yml homedir='~/Code/logpull/gnupg'
...

