---
- hosts: cluster
  vars_files:
    - ../vars/common.yml
  tasks:
    - name: Clone roller
      git: >
        dest=/opt/roller
        repo='git://github.com/akerl/roller.git'
    - name: Clone kernel configs
      git: >
        dest=/opt/roller/configs
        repo='git://github.com/akerl/kernels.git'
    - name: Roll the kernel
      command: /opt/roller/roller.py -k {{kernel_version}} -c {{kernel_version}} -r {{kernel_revision}}
...

