---
- hosts: cluster
  connection: local
  vars_files:
    - ../vars/common.yml
  tasks:
    - name: Find old host key in known_hosts
      shell: "awk '/{{inventory_hostname}}/ {print $NF}' ~/.ssh/known_hosts | head -n1"
      register: old_host_key
    - name: Remove old host key entries
      shell: sed -i '' 's|{{old_host_key.stdout}}|{{ansible_ssh_host_key_rsa_public}}|' ~/.ssh/known_hosts
      when: old_host_key.stdout != ansible_ssh_host_key_rsa_public and old_host_key.stdout != ''
    - name: Open two factor QR code
      command: open 'https://www.google.com/chart?chs=300x250&chld=M|0&cht=qr&chl=otpauth://totp/${inventory_hostname}?secret={{twofa.token}}'
    - name: Load GPG pubkey for node
      connection: ssh
      command: gpg -a --export {{inventory_hostname}}
      register: node_gpgkey
    - name: Wait for keyring to be available
      pause: prompt='Please ensure GPG keyring is available'
    - name: Remove any old keys for this node
      shell: >
        lockfile .block ;
        while gpg --yes --no-tty --batch --delete-key admin@{{inventory_hostname}}.{{domain}} ;
        do echo -n ;
        done ;
        rm -f .block
      ignore_errors: yes
    - name: Import new node key to keyring
      shell: echo '{{node_gpgkey.stdout}}' | gpg --import
      ignore_errors: yes
...

