---
- hosts: cluster
  connection: local
  serial: 1
  vars_files:
    - ../vars/common.yml
  tasks:
    - name: Open two factor QR code
      command: open 'https://www.google.com/chart?chs=300x250&chld=M|0&cht=qr&chl=otpauth://totp/${inventory_hostname}?secret={{twofa.token}}'
    - name: Load GPG pubkey for node
      connection: ssh
      command: gpg -a --export {{inventory_hostname}}
      register: node_gpgkey
    - name: Remove any old keys for this node
      shell: >
        lockfile .block ;
        while gpg --yes --no-tty --batch --delete-key admin@{{inventory_hostname}}.{{domain}} ;
        do echo -n ;
        done ;
        rm -f .block
      ignore_errors: yes
    - name: Import new node key to keyring
      shell: echo '{{node_gpgkey.stdout}}' | gpg --import
      ignore_errors: yes
...

