---
- hosts: cluster
  vars_files:
    - ../vars/common.yml
  tasks:
    - name: Set exim hostname
      lineinfile: >
        dest=/etc/mail/exim.conf
        regexp='^[ #]*primary_hostname ='
        line='primary_hostname = ${inventory_hostname}.${domain}'
    - name: Bind exim to localhost
      lineinfile: >
        dest=/etc/mail/exim.conf
        insertafter='^[ #]*primary_hostname ='
        regexp='^local_interfaces ='
        line='local_interfaces = 127.0.0.1'
    - name: Set exim domain list
      lineinfile: >
        dest=/etc/mail/exim.conf
        regexp='^domainlist local_domains ='
        line="domainlist local_domains = localhost : localhost.localdomain : ${inventory_hostname} : ${inventory_hostname}.${domain}"
    - name: Set root mail alias
      lineinfile: >
        dest=/etc/mail/aliases
        regexp='^[\s#]*root:'
        line='root: admin@${domain}'
    - name: Enable and start exim
      service: >
        name=exim
        state=restarted
        enabled=yes
...

