---
-   name: Remove FTP user
    user: name=ftp state=absent remove=yes force=yes

-   name: Add remote group
    group: state=present name=remote

-   name: Get root password
    connection: local
    keychain: keychain={{keychain}} service=root crypt=sha512
    register: root
-   name: Get admin user and password
    connection: local
    keychain: keychain={{keychain}} service=admin crypt=sha512
    register: admin
-   name: Adjust root user
    user: >
        name=root
        password={{root.password}}
        generate_ssh_key=yes
        ssh_key_bits=8096
        ssh_key_comment=root@{{inventory_hostname}}
        shell=/usr/bin/zsh
-   name: Add admin user
    user: >
        name={{admin.username}}
        password={{admin.password}}
        generate_ssh_key=yes
        ssh_key_bits=8192
        ssh_key_comment={{admin.username}}@{{inventory_hostname}}
        groups='wheel,remote'
        shell=/usr/bin/zsh

-   name: Preload known_hosts for root
    copy: >
        src=known_hosts
        dest=/root/.ssh/known_hosts
-   name: Preload known_hosts for admin
    copy: >
        src=known_hosts
        dest=/home/{{admin.username}}/.ssh/known_hosts
        owner={{admin.username}}
        group={{admin.username}}
...

