---
- hosts: all 
  vars_prompt:
    - name: root_pw
      prompt: Root password
      private: yes 
      confirm: yes 
      encrypt: sha512_crypt
  vars_files:
    - ../vars/common.yml
  tasks:
    - include: ../tasks/kernel.yml
    - pause: prompt="All remote configuration completed. Press enter for local actions"
    - include: ../tasks/local.yml
    - pause: prompt="Press enter to set root password and reboot server(s), or Ctrl-C A to stop playbook"
    - name: Schedule shutdown
      command: shutdown -r
    - name: Set root password
      user: name=root password=${root_pw}
...

