---
-   name: Identify swap device
    command: swapon --show=NAME --noheadings
    register: swapdev
-   name: Identify root device
    command: awk '/ext/ { print $1 }' /etc/fstab
    register: rootdev
-   name: Identify root format
    command: awk '/ext/ { print $3 }' /etc/fstab
    register: rootformat
-   name: Generate /etc/fstab
    template: src=fstab.j2 dest=/etc/fstab

-   name: Enable haveged
    service: name=haveged enabled=yes
-   name: Enable syslog-ng
    service: name=syslog-ng action=restart enabled=yes
-   name: Enable cronie
    service: name=cronie action=restart enabled=yes
-   name: Enable NTPd
    service: name=ntpd action=restart enabled=yes
-   name: Disable getty
    service: name=getty@tty1.service enabled=no

-   name: Remove specified files
    file: state=absent path={{item}}
    with_items: files.toremove
-   name: Recreate /boot/grub
    file: state=directory path=/boot/grub
...

